### ISSUE TITLE
Dev environment fails to build

### ISSUE THREAD

**Issue by avirshup** [Autodesk/notebook-molecular-visualization#33]
The master branch of this repo - currently on ded6a66dd0e2151fede520fa7fe9d405da9f4f4b - fails to build:

<details>
<summary>

 click for logs </summary>

```
$ python setup.py jsdeps
setup.py entered
$PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
running jsdeps
3.10.8
3.10.8
Installing build dependencies with npm.  This may take a while...

> molecule-2d-for-react@0.2.1 postinstall /root/notebook-molecular-visualization/js/node_modules/molecule-2d-for-react
> node nightwatch.conf.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'selenium-download'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/notebook-molecular-visualization/js/node_modules/molecule-2d-for-react/nightwatch.conf.js:2:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.27-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! molecule-2d-for-react@0.2.1 postinstall: `node nightwatch.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the molecule-2d-for-react@0.2.1 postinstall script 'node nightwatch.conf.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the molecule-2d-for-react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node nightwatch.conf.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs molecule-2d-for-react
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls molecule-2d-for-react
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/notebook-molecular-visualization/js/npm-debug.log
Traceback (most recent call last):
  File "setup.py", line 190, in <module>
    setup(**args)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 138, in run
    check_call(['npm', 'install'], cwd=node_root, stdout=sys.stdout, stderr=sys.stderr)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 1
root@6436cf018746:~/notebook-molecular-visualization# 
```

</details>

Pretty sure that this comes from a mismatch of the javascript libraries (being installed straight from NPM) and the github python code. If so, this may be unavoidable, but it would be great if there were a workaround.

**Comment by justinmc** [comment]
Whoops, this will make the package not work for anyone who installs this version 😄  It's definitely due to my recent travis work, should be a quick fix.

**Comment by justinmc** [comment]
Should be fixed in molecule-2d here: https://github.com/Autodesk/molecule-2d-for-react/pull/16

Probably also happening in 3d too, I'm taking a look...

**Comment by justinmc** [comment]
And here's the 3d fix: https://github.com/Autodesk/molecule-3d-for-react/pull/14

It looks like it's working for me now if I upgrade both of those modules to the latest version.  I'll open a PR that enforces that, and then this should be totally fixed.

**Comment by justinmc** [comment]
Fixed with https://github.com/Autodesk/notebook-molecular-visualization/pull/34
